from pydantic import BaseModel, Field
from typing import Literal, Optional


class ComparisonRow(BaseModel):
    dimension: str = Field(description="The comparison dimension/axis, e.g. 'Time complexity'")
    values: list[str] = Field(
        description="One short factual cell value per column, in the same order as ComparisonTable.columns"
    )


class ComparisonTable(BaseModel):
    """
    A dedicated comparison table generated by its own small LLM call.
    """
    applicable: bool = Field(
        description=(
            "True unless the query genuinely has no multi-item comparison structure. "
            "Should be true in almost all cases where >=2 candidate items were provided."
        )
    )
    caption: str = Field(default="Comparison", description="Short table title")
    columns: list[str] = Field(default_factory=list, description="2-5 named items being compared")
    rows: list[ComparisonRow] = Field(default_factory=list, description="3-8 comparison dimensions")


class NormalAnswer(BaseModel):
    direct_answer: str = Field(description="2-4 sentence direct answer to the user's question.")
    brief_context: Optional[str] = Field(
        default=None,
        description="EXACTLY ONE sentence explaining essential concepts ONLY if strictly necessary."
    )
    evidence: str = Field(
        description=(
            "Detailed summary of 2-4 key studies. For each study, explicitly cover: "
            "what it proposed, how it was evaluated, datasets used, main findings, and why it matters. "
            "If only one study exists, explain it in depth. Use markdown formatting."
        )
    )
    limitations: list[str] = Field(
        description=(
            "Expanded list of limitations. Must include specific methodological gaps such as: "
            "lack of replication, absence of user studies, limited benchmarks, lack of comparison "
            "with other techniques, or uncertain generalizability. Provide at least 3-5 distinct points."
        )
    )
    conclusion: str = Field(
        description=(
            "Briefly answer these three questions: "
            "1) What is supported by evidence? "
            "2) What remains uncertain? "
            "3) What should future work investigate?"
        )
    )
    confidence: Literal["High", "Medium", "Low"] = Field(
        description="Confidence in the answer."
    )
    confidence_explanation: str = Field(description="Brief explanation of the confidence level.")
    references: list[str] = Field(description="paper_ids of the 1-3 most relevant papers.")


class ResearchAnswer(BaseModel):
    executive_summary: str = Field(
        description="High-level summary of what the literature supports, what is uncertain, and the final answer."
    )
    background_concepts: str = Field(
        description="Explanation of relevant concepts from general to specific."
    )
    related_research: str = Field(
        description="Brief coverage of adjacent areas and explanation of their relevance to the query."
    )
    literature_review: str = Field(
        description="Synthesized summary of key papers. Synthesize, do not just list."
    )
    comparative_analysis: Optional[str] = Field(
        default=None,
        description="Comparison of methods, datasets, or findings."
    )
    evidence_assessment: str = Field(
        description="Strength, consistency, and limitations of the current evidence."
    )
    research_gaps: str = Field(
        description="Genuine unanswered questions or missing areas in the literature."
    )
    practical_implications: str = Field(
        description="Actionable implications and real-world applications."
    )
    final_answer: str = Field(
        description="The definitive, synthesized answer to the user's original question."
    )
    confidence: Literal["High", "Medium", "Low"] = Field(
        description="Confidence level based on evidence quality/quantity."
    )
    confidence_explanation: str = Field(
        description="Brief explanation based on evidence quality/quantity."
    )
    references: list[str] = Field(description="paper_ids of high-quality relevant papers.")


class QueryUnderstanding(BaseModel):
    main_topic: str = Field(description="The core research topic")
    subtopics: list[str] = Field(description="Important subtopics or facets")
    objectives: list[str] = Field(description="Research objectives or goals")
    methods_techniques: list[str] = Field(description="Methods, algorithms, models, and techniques")
    application_domain: str = Field(description="The specific application domain")
    acronyms: dict[str, str] = Field(description="Acronyms and their expanded forms")
    entities: list[str] = Field(description="Important entities, datasets, or frameworks")
    academic_terminology: list[str] = Field(
        description="Academic terminology commonly used in literature for this topic"
    )


class QueryPlan(BaseModel):
    rewritten_queries: list[str] = Field(description="2-3 semantically equivalent queries using academic phrasing")
    expanded_queries: list[str] = Field(description="2-3 broader/narrower/related concepts to improve recall")
    method_queries: list[str] = Field(description="1-2 queries focusing on specific algorithms/techniques")
    domain_queries: list[str] = Field(description="1-2 queries focusing on the application domain")
    fallback_queries: list[str] = Field(description="1-2 very broad queries if the topic is too narrow")


class NormalizedQuery(BaseModel):
    search_terms: list[str] = Field(description="5 distinct technical search phrases")
    is_definitional: bool = Field(description="True if user wants foundational understanding")
    likely_cs_relevant: bool = Field(default=True, description="True if arXiv is sensible source")
    domain_full: Optional[str] = Field(default=None)
    domain_keywords: list[str] = Field(default_factory=list)
    mandatory_domain_keywords: Optional[list[str]] = Field(default=None)


class PaperSummaryItem(BaseModel):
    paper_id: str
    key_contribution: str
    methodology: str
    findings: str
    relevance_to_query: str
    evidence_type: Literal["direct", "supporting", "background"] = Field(default="supporting")
    key_metrics: list[str] = Field(
        default_factory=list,
        description=(
            "Any exact numeric figures explicitly stated in the paper's abstract/text relevant to comparing methods. "
            "Copy numbers verbatim from the source text. Leave empty if no such figures are stated."
        )
    )


class BatchPaperSummaries(BaseModel):
    summaries: list[PaperSummaryItem]


class FinalAnswer(BaseModel):
    answer: str
    confidence: float
    papers_used: list[str]
    coverage_gaps: list[str] = Field(default_factory=list)
    domain_caveat: Optional[str] = Field(default=None)


class RetryDecision(BaseModel):
    should_retry: bool
    refined_query: Optional[str] = Field(default=None)
    reason: str


class FollowupAnswer(BaseModel):
    answer: str
    sources_used: list[str]
    grounded: bool


class ClusterSection(BaseModel):
    theme: str
    content: str
    paper_ids: list[str]


class ClusteredFinalAnswer(BaseModel):
    sections: list[ClusterSection]
    overview: str
    confidence: float
    coverage_gaps: list[str] = Field(default_factory=list)



class PlannedModule(BaseModel):
    module_id: str = Field(description="Module id from the module library")
    importance: int = Field(default=50, ge=0, le=100)
    reason: Optional[str] = Field(default=None)


class ReportPlanLLM(BaseModel):
    primary_intent: Literal[
        "explain",
        "compare",
        "research",
        "decision",
        "design",
        "forecast",
        "strategy",
        "troubleshooting",
        "planning",
        "tutorial",
        "coding",
        "mathematical",
        "medical",
        "legal",
        "scientific",
        "mixed",
    ] = "research"

    secondary_intents: list[str] = Field(default_factory=list)

    information_needs: list[str] = Field(
        default_factory=list,
        description=(
            "Atomic information needs, e.g. background, mechanism, comparison, risk, "
            "cost, implementation, forecast, evidence, recommendation."
        )
    )

    complexity_score: int = Field(default=50, ge=0, le=100)

    depth: Literal["low", "medium", "high"] = Field(default="medium")

    reference_policy: Literal[
        "minimal",
        "standard",
        "research",
        "documentation",
        "none",
    ] = "standard"

    reasoning_policy: Literal[
        "evidence_only",
        "evidence_plus_analysis",
        "first_principles_allowed",
        "speculative_allowed",
    ] = "evidence_plus_analysis"

    domain_guardrails: list[str] = Field(default_factory=list)

    modules: list[PlannedModule] = Field(default_factory=list)

    latency_notice: Optional[str] = Field(default=None)


class SectionOutput(BaseModel):
    module_id: str
    title: str
    content: str
    cited_paper_ids: list[int] = Field(
        default_factory=list,
        description=(
            "The integer N from each [paper_id=N] marker cited in this section's content. "
            "Plain integers, e.g. [0, 2, 5] — not quoted strings."
        ),
    )
    evidence_status: Literal[
        "strong",
        "mixed",
        "weak",
        "none",
        "not_applicable",
    ] = "none"
    confidence: Literal["high", "medium", "low"] = "medium"


class SectionBatch(BaseModel):
    sections: list[SectionOutput]


class DynamicConfidence(BaseModel):
    evidence_quality: Literal["high", "medium", "low"]
    answer_confidence: Literal["high", "medium", "low"]
    prediction_confidence: Optional[Literal["high", "medium", "low"]] = None
    recommendation_confidence: Optional[Literal["high", "medium", "low"]] = None
    data_completeness: Literal["high", "medium", "low"]
    uncertainty: Literal["low", "moderate", "high"]
    explanation: str


class ReportCoverageCheck(BaseModel):
    fully_covers_query: bool = Field(
        description=(
            "True if every specific detail/constraint in the user's query and every required "
            "planned module is addressed or explicitly flagged as unavailable."
        )
    )
    missing_or_assumed: list[str] = Field(default_factory=list)
    missing_modules: list[str] = Field(default_factory=list)
    revision_instruction: str = Field(default="")